language: go
go:
  - 1.13.x
  - 1.14.x

script:
  - curl -sSL "https://github.com/gotestyourself/gotestsum/releases/download/v0.4.2/gotestsum_0.4.2_linux_amd64.tar.gz" | sudo tar -xz -C /usr/local/bin gotestsum
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.25.0
  - time make build

after_success:
  - echo "travis go version='$TRAVIS_GO_VERSION'"