ignored_tests:
  go:
    - package: github.com/databricks/terraform-provider-databricks/scim_test
      test_name: TestAccGroupsUpdateDisplayName
      comment: Failures due to read-after-write inconsistency. Tracked in https://databricks.atlassian.net/browse/ES-1100061
    - package: github.com/databricks/terraform-provider-databricks/scim_test
      test_name: TestMwsAccGroupDataSplitMembers
      comment: Failures due to read-after-write inconsistency. Tracked in https://databricks.atlassian.net/browse/ES-1100061
    - package: github.com/databricks/terraform-provider-databricks/scim_test
      test_name: TestAccServicePrincipalResourceOnAws
      comment: Failures due to read-after-write inconsistency. Tracked in https://databricks.atlassian.net/browse/ES-1100061
    - package: github.com/databricks/terraform-provider-databricks/scim_test
      test_name: TestMwsAccServicePrincipalResourceOnAws
      comment: Failures due to read-after-write inconsistency. Tracked in https://databricks.atlassian.net/browse/ES-1100061
    - package: github.com/databricks/terraform-provider-databricks/mws_test
      test_name: TestUcAccAssignGroupToWorkspace
      comment: Failures due to read-after-write inconsistency. Tracked in https://databricks.atlassian.net/browse/ES-1100061
    - package: github.com/databricks/terraform-provider-databricks/vectorsearch_test
      test_name: TestUcAccVectorSearchEndpoint
      comment: Failure due to read-after-create inconsistency. https://databricks.atlassian.net/browse/ES-1243690
    - package: github.com/databricks/terraform-provider-databricks/scim_test
      test_name: TestAccServicePrincipalResourceOnAzure
      comment: Failure due to read-after-write inconsistency. Tracked in https://databricks.atlassian.net/browse/ES-1100061