change_types:
  - message: New Features and Improvements
    tag: "[Feature]"
  - message: Bug Fixes
    tag: "[Fix]"
  - message: Documentation
    tag: "[Docs]" 
  - message: Internal Changes
    tag: "[Internal]"
  - message: Dependency Updates
    tag: "[Dependency]"
  - message: Exporter
    tag: "[Exporter]"
  # Default for messages without a tag
  - message: Other Changes