name: Validate Commit Message

on:
  pull_request:
    types: [opened, synchronize, edited]
  merge_group:
      types: [checks_requested] 

jobs:
  validate:
    runs-on:
      group: ubuntu-runners
      labels: ubuntu-20.04-16core
    # GitHub required checks are shared between PRs and the Merge Queue.
    # Since there is no PR title on Merge Queue, we need to trigger and
    # skip this test for Merge Queue to succeed.
    if: github.event_name == 'pull_request' 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate Tag
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          TAG=$(echo "$TITLE" | sed -ne 's/\[\(.*\)\].*/\1/p')
          if grep -q "tag: \"\[$TAG\]\"" .codegen/changelog_config.yml; then 
            echo "Valid tag found: [$TAG]"
          else 
            echo "Invalid or missing tag in commit message: [$TAG]" 
            exit 1
          fi