name: PR Target Injection PoC

on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  poc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code (VULNERABLE PATTERN)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: PoC Execution
        run: |
          echo "H1-vishalkumar9570"
          echo "PR SHA: ${{ github.event.pull_request.head.sha }}"
          whoami
