name: test-push

on:
  
  workflow_dispatch:

  # Specific file
  pull_request:
    paths:
      -'.github/workflows/*.yml'



jobs:
  tag:
    environment: "release-is"
    runs-on:
      group: databricks-deco-testing-runner-group
      labels: ubuntu-latest-deco
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.DECO_SDK_TAGGING_APP_ID }}
          private-key: ${{ secrets.DECO_SDK_TAGGING_PRIVATE_KEY }}
  
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
  
      # NOTE: actions/create-github-app-token automatically masks the output token,
      # so the token is not exposed in the logs even as part of the remote.
      - name: Set up Git configuration
        run: |
          git config user.name "Databricks SDK Release Bot"
          git config user.email "DECO-SDK-Tagging[bot]@users.noreply.github.com"

