name: Validate openapi sha

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate SHA
        run: |
          Version=$(go list -m -json github.com/databricks/databricks-sdk-go | jq -r ".Version")
          echo "Version: $Version"
          OPENAPI_SHA_GO_SDK=$(curl https://raw.githubusercontent.com/databricks/databricks-sdk-go/$Version/.codegen/_openapi_sha)
          OPENAPI_SHA=$(cat .codegen/_openapi_sha)
          if [ "$OPENAPI_SHA_GO_SDK" != "$OPENAPI_SHA" ]; then
            echo "OpenAPI SHA mismatch"
            exit 1
          else 
            echo "OpenAPI SHA match"
          fi